[tool.poetry]
name = "django_bootstrap"
version = "0.0.1"
description = "A Django base installation  to play around with"
authors = ["Martijn Jacobs <martijn@devopsconsulting.nl>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/maerteijn/django-bootstrap"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.7"
]
packages = [
    { include = "django_bootstrap" },
]

include = ["django_manage.py"]

[[tool.poetry.source]]
name = "devpi"
url = "http://localhost:3141/root/pypi/+simple/"

[tool.poetry.dependencies]
python = "^3.7"
Django = "~2.2"
psycopg2-binary = "~2.8"

[tool.poetry.dev-dependencies]
flake8 = "~3.7"
flake8-isort =  "^2.7.0"
black = {version = "^19.3-beta.0",allows-prereleases = true}
pytest = "~^5.0"
pytest-django = "^3.5.1"
pytest-cov = "~2.7.1"

[tool.poetry.scripts]
"manage.py" =  "django_manage:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
