[tool.poetry]
name = "django_bootstrap"
version = "0.0.1"
description = "A Django base installation  to play around with"
authors = ["Martijn Jacobs <martijn@devopsconsulting.nl>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/maerteijn/django-bootstrap"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.7"
]
packages = [
    { include = "django_bootstrap" },
]

include = ["django_manage.py"]

[[tool.poetry.source]]
name = "devpi"
url = "http://localhost:3141/root/pypi/+simple/"

[tool.poetry.dependencies]
python = "^3.7"
Django = "~3.0"
psycopg2-binary = "~2.8"

[tool.poetry.dev-dependencies]
flake8 = "~3.7"
flake8-isort =  "^2.7.0"
black = {version = "^19.10b0 ",allow-prereleases = true}
pytest = "~^5.3"
pytest-django = "~3.7"
pytest-cov = "~2.8"

[tool.poetry.scripts]
"manage.py" =  "django_manage:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
force_grid_wrap=0
include_trailing_comma=true
line_length=88
multi_line_output=3
use_parentheses=true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "django_bootstrap.settings"
testpaths = "tests/"
addopts = "--no-migrations --create-db --cov=django_bootstrap"

[tool.coverage.run]
omit = "*/migrations/*"

[tool.coverage.report]
show_missing = true

